# Generated by Django 5.1.3 on 2024-11-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='old dojo'),
        ),
    ]
